name: C/C++ CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Makefile
      run: minggw32-make -f Makefile
    - name: Tests
      run: mingw32-make -f Tests.mk

